server:
  port: 9001

spring:
  mongodb:
    uri: mongodb://127.0.0.1:27017/market
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  upload:
    path: static/images/market/

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-footer: false
    enable-request-cache: true
